/** Pre-renders the site QR as an SVG constant for the server-rendered gate page (no runtime assets). */
import { writeFileSync } from "node:fs";
import { default as qrcode } from "../public/vendor/qrcode.mjs";
const URL_ = "https://pa.solidstart.jp/";
const qr = qrcode(0, "M"); qr.addData(URL_); qr.make();
const svg = qr.createSvgTag({ cellSize: 4, margin: 4, scalable: true }).replace(/<svg /, '<svg class="qr" role="img" aria-label="' + URL_ + '" ');
writeFileSync("src/qr-site.ts", `// Generated by scripts/gen-qr.mjs — QR of ${URL_}\nexport const SITE_URL = ${JSON.stringify(URL_)};\nexport const SITE_QR_SVG = ${JSON.stringify(svg)};\n`);
console.log("src/qr-site.ts:", svg.length, "bytes of SVG for", URL_);
